ALTER TABLE crestdata DROP COLUMN pcmh_date_07, 
DROP COLUMN bc_status_09,
DROP COLUMN note_date_15b,
DROP COLUMN note_diary_date_15d,
DROP COLUMN note_print_15a,
DROP COLUMN note_15c,
DROP COLUMN note_type_12,
DROP COLUMN ctl_expiry_10,
DROP COLUMN forename1_11a,
DROP COLUMN forename2_11b,
DROP COLUMN surname_11c,
DROP COLUMN linked_case_17,
DROP COLUMN non_end_16a,
DROP COLUMN non_reason_16b,
DROP COLUMN non_start_11,
DROP COLUMN urn_13;